"""Type stubs for image_utils module."""

from typing import Any, Dict

def native_kmeans_quantize(img: Any, k: int = 8, max_iter: int = 10) -> Any: ...
def sklearn_kmeans_quantize(img: Any, k: int = 8) -> Any: ...
def apply_transformation(img: Any, transformation: str) -> Any: ...
def extract_exif_data(img: Any) -> Dict[str, Any]: ...
def calculate_dest_key(
    source_key: str, source_prefix: str, dest_prefix: str
) -> str: ...
