name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install uv
      - run: uv venv && uv install
      - run: ruff check .
      - run: ruff format --check .
      - run: mypy .
      - run: pytest
      - run: uv build